#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "t384_mini2_protocol.h"

int main(void)
{
    static const uint8_t expected_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x46u, 0x00u,
        0x01u, 0x01u, 0x1Eu, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x06u, 0x3Bu,
    };
    static const uint8_t picture_mode_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x45u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0xFBu, 0xC0u,
    };
    /* OEM MINI2 UART V0.4 sheet 2 rows 71/92/93, not generated by this test. */
    static const uint8_t detector30_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u, 0x10u, 0x10u, 0x44u,
        0x00u, 0x1Eu, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x5Cu, 0x9Cu,
    };
    static const uint8_t detector60_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u, 0x10u, 0x10u, 0x44u,
        0x00u, 0x3Cu, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x16u, 0xF4u,
    };
    static const uint8_t dvp60_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u, 0x10u, 0x10u, 0x46u,
        0x00u, 0x01u, 0x01u, 0x3Cu, 0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x81u, 0xDCu,
    };
    static const uint8_t tpd_mode_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x45u, 0x00u,
        0x01u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x8Eu, 0xC3u,
    };
    static const uint8_t valid_ack[] = {
        0xBEu, 0xAAu, 0x01u, 0x00u, 0x00u,
        0x7Bu, 0x54u, 0xEBu, 0xAAu,
    };
    static const uint8_t detector_response[] = {
        0xBEu, 0xAAu, 0x02u, 0x00u, 0x00u,
        0x1Eu, 0x52u, 0x09u, 0xEBu, 0xAAu,
    };
    static const uint8_t digital_response[] = {
        0xBEu, 0xAAu, 0x05u, 0x00u, 0x00u,
        0x01u, 0x01u, 0x1Eu, 0x00u,
        0x0Du, 0x37u, 0xEBu, 0xAAu,
    };
    static const uint8_t detector_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x84u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x01u, 0x00u, 0x00u, 0x00u,
        0xEFu, 0xB1u,
    };
    static const uint8_t digital_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x86u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x04u, 0x00u, 0x00u, 0x00u,
        0x68u, 0xFBu,
    };
    static const uint8_t pn_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x01u, 0x01u, 0x81u, 0x00u,
        0x06u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x20u, 0x00u, 0x00u, 0x00u,
        0xB7u, 0x16u,
    };
    static const uint8_t sn_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x01u, 0x01u, 0x81u, 0x00u,
        0x07u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x20u, 0x00u, 0x00u, 0x00u,
        0xC2u, 0x15u,
    };
    static const uint8_t stream_mode_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x85u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x01u, 0x00u, 0x00u, 0x00u,
        0x8Eu, 0xCAu,
    };
    static const uint8_t auto_ffc_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x02u, 0x81u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x01u, 0x00u, 0x00u, 0x00u,
        0x78u, 0x34u,
    };
    static const uint8_t module_temp_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x91u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x02u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x6Au,
    };
    static const uint8_t uptime_query[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u,
        0x10u, 0x10u, 0x93u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x00u, 0x00u, 0x00u,
        0x04u, 0x00u, 0x00u, 0x00u,
        0x5Bu, 0xBBu,
    };
    static const uint8_t stream_mode_response[] = {
        0xBEu, 0xAAu, 0x02u, 0x00u, 0x00u,
        0x03u, 0xCEu, 0xCAu, 0xEBu, 0xAAu,
    };
    static const uint8_t auto_ffc_response[] = {
        0xBEu, 0xAAu, 0x02u, 0x00u, 0x00u,
        0x01u, 0x8Cu, 0xEAu, 0xEBu, 0xAAu,
    };
    static const uint8_t module_temp_response[] = {
        0xBEu, 0xAAu, 0x03u, 0x00u, 0x00u,
        0xAAu, 0x0Cu, 0x3Du, 0x7Au, 0xEBu, 0xAAu,
    };
    static const uint8_t uptime_response[] = {
        0xBEu, 0xAAu, 0x05u, 0x00u, 0x00u,
        0xD7u, 0x01u, 0x00u, 0x00u,
        0xEBu, 0x98u, 0xEBu, 0xAAu,
    };
    uint8_t command[T384_MINI2_DVP30_COMMAND_BYTES];
    t384_mini2_build_video_command(command, 0x44u, 30u, 0u, 0u);
    assert(memcmp(command, detector30_command, sizeof(command)) == 0);
    t384_mini2_build_video_command(command, 0x44u, 60u, 0u, 0u);
    assert(memcmp(command, detector60_command, sizeof(command)) == 0);
    t384_mini2_build_video_command(command, 0x46u, 1u, 1u, 60u);
    assert(memcmp(command, dvp60_command, sizeof(command)) == 0);
    static const uint8_t vtemp_command[] = {
        0x55u, 0x43u, 0x49u, 0x12u, 0x00u, 0x01u, 0x0Fu, 0x86u,
        0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
        0x00u, 0x02u, 0x00u, 0x00u, 0x00u, 0x87u, 0x46u,
    };
    t384_mini2_build_vtemp_query_command(command);
    assert(memcmp(command, vtemp_command, sizeof(vtemp_command)) == 0);
    uint8_t status = 0xFFu;

    t384_mini2_build_dvp30_command(command);
    if (memcmp(command, expected_command, sizeof(command)) != 0) {
        return 1;
    }
    t384_mini2_build_stream_mode_command(
        command, T384_MINI2_STREAM_MODE_PICTURE);
    if (memcmp(command, picture_mode_command, sizeof(command)) != 0) {
        return 22;
    }
    t384_mini2_build_stream_mode_command(
        command, T384_MINI2_STREAM_MODE_TPD_Y16);
    if (memcmp(command, tpd_mode_command, sizeof(command)) != 0) {
        return 23;
    }
    if (command[7] == 0x49u) {
        return 24;
    }
    if (!t384_mini2_parse_generic_ack(valid_ack, &status) || status != 0u) {
        return 2;
    }
    uint8_t corrupt_ack[T384_MINI2_GENERIC_ACK_BYTES];
    memcpy(corrupt_ack, valid_ack, sizeof(corrupt_ack));
    corrupt_ack[5] ^= 1u;
    if (t384_mini2_parse_generic_ack(corrupt_ack, &status)) {
        return 3;
    }
    const uint8_t *data = NULL;
    uint16_t data_length = 0u;
    if (!t384_mini2_parse_response(detector_response,
                                   sizeof(detector_response), &status, &data,
                                   &data_length) || status != 0u ||
        data_length != 1u || data[0] != 0x1Eu) {
        return 6;
    }
    if (!t384_mini2_parse_response(digital_response, sizeof(digital_response),
                                   &status, &data, &data_length) || status != 0u ||
        data_length != 4u || data[0] != 1u || data[1] != 1u ||
        data[2] != 0x1Eu) {
        return 7;
    }
    t384_mini2_build_query_command(command, 0x84u, 1u);
    if (memcmp(command, detector_query, sizeof(command)) != 0) {
        return 8;
    }
    t384_mini2_build_query_command(command, 0x86u, 4u);
    if (memcmp(command, digital_query, sizeof(command)) != 0) {
        return 9;
    }
    t384_mini2_build_info_query_command(command, 0x01u, 32u);
    if (command[5] != 0x01u || command[6] != 0x01u ||
        command[7] != 0x81u || command[9] != 0x01u ||
        command[17] != 32u ||
        t384_mini2_crc16_xmodem(command + 5u, 16u) !=
            ((uint16_t)command[21] | ((uint16_t)command[22] << 8))) {
        return 10;
    }
    t384_mini2_build_info_query_command(command, 0x02u, 11u);
    if (command[9] != 0x02u || command[17] != 11u ||
        t384_mini2_crc16_xmodem(command + 5u, 16u) !=
            ((uint16_t)command[21] | ((uint16_t)command[22] << 8))) {
        return 11;
    }
    t384_mini2_build_info_query_command(command, 0x06u, 32u);
    if (memcmp(command, pn_query, sizeof(command)) != 0) {
        return 12;
    }
    t384_mini2_build_info_query_command(command, 0x07u, 32u);
    if (memcmp(command, sn_query, sizeof(command)) != 0) {
        return 13;
    }
    t384_mini2_build_query_command(command, 0x85u, 1u);
    if (memcmp(command, stream_mode_query, sizeof(command)) != 0) {
        return 14;
    }
    t384_mini2_build_class_query_command(command, 0x02u, 0x81u, 0u, 1u);
    if (memcmp(command, auto_ffc_query, sizeof(command)) != 0) {
        return 15;
    }
    t384_mini2_build_query_command(command, 0x91u, 2u);
    if (memcmp(command, module_temp_query, sizeof(command)) != 0) {
        return 16;
    }
    t384_mini2_build_query_command(command, 0x93u, 4u);
    if (memcmp(command, uptime_query, sizeof(command)) != 0) {
        return 17;
    }
    if (!t384_mini2_parse_response(stream_mode_response,
                                   sizeof(stream_mode_response), &status,
                                   &data, &data_length) ||
        status != 0u || data_length != 1u || data[0] != 3u) {
        return 18;
    }
    if (!t384_mini2_parse_response(auto_ffc_response,
                                   sizeof(auto_ffc_response), &status,
                                   &data, &data_length) ||
        status != 0u || data_length != 1u || data[0] != 1u) {
        return 19;
    }
    if (!t384_mini2_parse_response(module_temp_response,
                                   sizeof(module_temp_response), &status,
                                   &data, &data_length) ||
        status != 0u || data_length != 2u || data[0] != 0xAAu ||
        data[1] != 0x0Cu) {
        return 20;
    }
    if (!t384_mini2_parse_response(uptime_response,
                                   sizeof(uptime_response), &status,
                                   &data, &data_length) ||
        status != 0u || data_length != 4u || data[0] != 0xD7u ||
        data[1] != 0x01u || data[2] != 0u || data[3] != 0u) {
        return 21;
    }
    t384_mini2_build_video_command(command, 0x46u, 0x00u, 0x00u, 0x00u);
    if (command[7] != 0x46u || command[9] != 0x00u ||
        command[10] != 0x00u || command[11] != 0x00u ||
        t384_mini2_crc16_xmodem(command + 5u, 16u) !=
            ((uint16_t)command[21] | ((uint16_t)command[22] << 8))) {
        return 4;
    }
    t384_mini2_build_video_command(command, 0x4Au, 0x00u, 0x00u, 0x00u);
    if (command[7] != 0x4Au || command[9] != 0x00u ||
        t384_mini2_crc16_xmodem(command + 5u, 16u) !=
            ((uint16_t)command[21] | ((uint16_t)command[22] << 8))) {
        return 5;
    }
    puts("T384 MINI2 UART command/ACK vectors passed");
    return 0;
}
