#!/usr/bin/env python3
"""Generate the C include for the embedded T384 device console."""

from __future__ import annotations

import argparse
import pathlib
import sys


PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = PROJECT_ROOT / "web" / "device_console.html"
DEFAULT_OUTPUT = (PROJECT_ROOT / "tests" / "ch32h417_t384_ncm" /
                  "Common" / "App" / "device_console_html.inc")


def c_quote(text: str) -> str:
    lines = []
    for offset in range(0, len(text), 400):
        chunk = text[offset:offset + 400]
        quoted = (chunk.replace("\\", "\\\\")
                       .replace('"', '\\"')
                       .replace("\r", "\\r")
                       .replace("\n", "\\n"))
        lines.append(f'    "{quoted}"')
    return "\n".join(lines) + "\n"


def render(source: pathlib.Path) -> str:
    html = source.read_text(encoding="utf-8")
    response = (
        "HTTP/1.0 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Cache-Control: no-store\r\n"
        "Connection: close\r\n\r\n" + html
    )
    return "/* Generated by tools/embed_device_console.py. */\n" + c_quote(response)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", type=pathlib.Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    source = args.source if args.source.is_absolute() else PROJECT_ROOT / args.source
    output = args.output if args.output.is_absolute() else PROJECT_ROOT / args.output
    expected = render(source)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {output.relative_to(PROJECT_ROOT)}", file=sys.stderr)
            return 1
        print("T384 device console embed is current")
        return 0
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {output.relative_to(PROJECT_ROOT)} ({len(expected)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
