#!/usr/bin/env python3
"""Generate the C include for the embedded T384 device console."""

from __future__ import annotations

import argparse
import gzip
import io
import pathlib
import sys


PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = PROJECT_ROOT / "web" / "device_console.html"
DEFAULT_OUTPUT = (PROJECT_ROOT / "tests" / "ch32h417_t384_ncm" /
                  "Common" / "App" / "device_console_html.inc")


def c_quote(text: str) -> str:
    lines = []
    for offset in range(0, len(text), 400):
        chunk = text[offset:offset + 400]
        quoted = (chunk.replace("\\", "\\\\")
                       .replace('"', '\\"')
                       .replace("\r", "\\r")
                       .replace("\n", "\\n"))
        lines.append(f'    "{quoted}"')
    return "\n".join(lines) + "\n"


def render(source: pathlib.Path) -> str:
    html = source.read_text(encoding="utf-8")
    response = (
        "HTTP/1.0 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Cache-Control: no-store\r\n"
        "Connection: close\r\n\r\n" + html
    )
    return "/* Generated by tools/embed_device_console.py. */\n" + c_quote(response)


def c_hex(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(lines) + "\n"


def gzip_html(html: bytes) -> bytes:
    """Return a reproducible gzip member without embedding a source filename."""
    output = io.BytesIO()
    with gzip.GzipFile(fileobj=output, mode="wb", mtime=0) as stream:
        stream.write(html)
    return output.getvalue()


def render_gzip(source: pathlib.Path) -> str:
    compressed = gzip_html(source.read_bytes())
    response = (
        "HTTP/1.0 200 OK\r\n"
        "Content-Type: text/html; charset=utf-8\r\n"
        "Content-Encoding: gzip\r\n"
        f"Content-Length: {len(compressed)}\r\n"
        "Cache-Control: no-store\r\n"
        "Connection: close\r\n\r\n"
    ).encode("ascii") + compressed
    return ("// Generated by tools/embed_device_console.py; gzip mtime=0.\n" +
            c_hex(response))


def relative_name(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--source", type=pathlib.Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--gzip-output", type=pathlib.Path,
                        help="also generate a gzip HTTP-response C include")
    args = parser.parse_args()
    source = args.source if args.source.is_absolute() else PROJECT_ROOT / args.source
    output = args.output if args.output.is_absolute() else PROJECT_ROOT / args.output
    expected = render(source)
    gzip_output = None
    gzip_expected = None
    if args.gzip_output is not None:
        gzip_output = (args.gzip_output if args.gzip_output.is_absolute()
                       else PROJECT_ROOT / args.gzip_output)
        gzip_expected = render_gzip(source)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {relative_name(output)}", file=sys.stderr)
            return 1
        if (gzip_output is not None and
                (not gzip_output.exists() or
                 gzip_output.read_text(encoding="utf-8") != gzip_expected)):
            print(f"stale generated file: {relative_name(gzip_output)}", file=sys.stderr)
            return 1
        print("T384 device console embed is current")
        return 0
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {relative_name(output)} ({len(expected)} bytes)")
    if gzip_output is not None:
        gzip_output.write_text(gzip_expected, encoding="utf-8", newline="\n")
        print(f"wrote {relative_name(gzip_output)} ({len(gzip_expected)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
